language: php

php:
    - 5.6
    - 7.0
    - 7.1

install:
  - composer require satooshi/php-coveralls:~0.6@stable

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
    - cp .env.example .env
    - echo "APP_KEY=SmduSUaF1KAAwhRIP6yLHgw0KzebWC6Z" >> .env
    - echo "DB_CONNECTION=sqlite" >> .env
    - touch database/homestead.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php artisan key:generate
    - php artisan migrate --database=testing --force
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
